### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by mariomulansky** [comment]
Thanks for the PR. I'm very happy to see someone looked into Python3 support here. I will add Python3 to the CI tests and then merge and make a new release.

**Comment by ignatenkobrain** [comment]
I already added py3 to the CI.

**Comment by mariomulansky** [comment]
Ah right, great! Could you create a PR against develop instead of master though? Thanks!

**Comment by ignatenkobrain** [comment]
#19

**Pull request closed without merging**
